name: "Mores Maven Actions"
description: "Support Maven actions (build, deploy, release)"

inputs:
  maven_settings_xml:
    description: "Path to maven settings.xml"
    required: true
    default: ${{ github.action_path }}/settings.xml
  maven_repository:
    description: "Path to maven repository (default ~/.m2/repository)"
    required: true
    default: '~/.m2/repository'

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - name: Set up JDK 11
    uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'adopt'

  - name: Cache maven packages
    uses: actions/cache@v2
    with:
      path: ${{ inputs.maven_repository }}
      key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      restore-keys: ${{ runner.os }}-m2-

  - id: set-maven-ops
    name: Set MAVEN_OPTS parameters
    run: |
      echo "MAVEN_OPTS=-Dmaven.repo.local=${{ inputs.maven_repository }}" >> $GITHUB_ENV
      echo "Creating alias for mvn command"
      alias mvn="mvn -s ${{ inputs.maven_settings_xml }} --batch-mode --update-snapshots"
    shell: sh
