name: "Mores Maven Actions"
description: "Support Maven actions (build, deploy, release)"

inputs:
  maven_repository:
    description: "Path to maven repository (default ~/.m2/repository)"
    required: true
    default: '~/.m2/repository'

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - name: Set up JDK 11
    uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'adopt'

  - name: Cache maven packages
    uses: actions/cache@v2
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-m2
      restore-keys: ${{ runner.os }}-m2

  - id: set-maven-ops
    name: Set MAVEN_OPTS parameters
    run: |
      echo "MAVEN_OPTS=-Dmaven.repo.local=${{ inputs.maven_repository }}" >> $GITHUB_ENV
      echo "MAVEN_CLI_OPTS=-s ${{ github.action_path }}/settings.xml --batch-mode --update-snapshots" >> $GITHUB_ENV
    shell: sh
